version: "3"
services:
    strapi:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - 1337:1337
        depends_on:
            - db
        environment:
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - DATABASE_NAME=strapi
            - DATABASE_USERNAME=strapi
            - DATABASE_PASSWORD=strapi

    db:
        container_name: postgres
        image: "postgres:latest"
        environment:
            - POSTGRES_USER=strapi
            - POSTGRES_PASSWORD=strapi
            - POSTGRES_DB=strapi
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
